### ISSUE TITLE
Update Queries and Responses

### ISSUE THREAD

**Issue by lasyaEd** [umcchavali/t-c#13]
In queriesResponses.json update queries and responses. 
 
1) Responses need to be shorter. May be a couple of words - 3 words to a small sentence.

Reproducibility:
clone repo locally.
create a venv, pip install -r requirements.txt
create a .env file with OPENAI_API_KEY=-----------------------I will give it to you-------------
change the query responses, save them and then
run simple_rag.ipynb

**Comment by lasyaEd** [comment]
Need test results once completed to put them in document writeup.

3. Testing artifacts (e.g., user feedback forms, test results)

**Comment by Hiranyabandi** [comment]
[updates queries and responses.json](https://github.com/user-attachments/files/17853620/updates.queries.and.responses.json)

**Comment by Hiranyabandi** [comment]
These are the updates queries.
[
    {
      "question": "Does METTLER TOLEDO's waive any provision?",
      "answer": "No, METTLER TOLEDO does not waive any provision."
    },
    {
      "question": "What rights do users grant Amazon when posting reviews or comments?",
      "answer": "Nonexclusive, royalty-free, perpetual, irrevocable, and sublicensable rights."
    },
    {
      "question": "What happens if a product offered by Amazon is not as described?",
      "answer": "Return it in unused condition."
    },
    {
      "question": "What permissions might you grant when using Amazon-created apps?",
      "answer": "Device-specific permissions like location or camera access."
    },
    {
      "question": "How does Apple’s advertising platform differ from others regarding user tracking?",
      "answer": "It does not link user/device data with third-party data or share data with brokers."
    },
    {
      "question": "Can Audi revoke access to the complimentary charging promotion without notice, and under what conditions?",
      "answer": "Yes, Audi can revoke access if there is suspected excessive, fraudulent, or unauthorized use or violation of any terms."
    },
    {
      "question": "How does Audi handle situations where a technological change renders certain service-related equipment obsolete?",
      "answer": "Audi is not obligated to design or provide replacement equipment, leaving users to bear the cost."
    },
    {
      "question": "Can I use Chick-fil-A rewards at all locations?",
      "answer": "No, rewards may not be accepted at licensed or non-traditional locations like airports or colleges."
    },
    {
      "question": "What is Chick-fil-A's policy on arbitration?",
      "answer": "Disputes are resolved through binding arbitration or small claims court, with a waiver of class action rights."
    },
    {
      "question": "What is Costco policy on handling user-generated content that may violate copyright or trademark laws?",
      "answer": "Costco may remove infringing content and take legal action against users who violate copyright laws."
    },
    {
      "question": "How does Qdoba's new rewards program differ from its previous program in terms of point conversion and redemption?",
      "answer": "24-to-1 point conversion"
    },
    {
      "question": "What are the terms regarding Qdoba's Q-Cash gift cards?",
      "answer": "Food purchases only allowed"
    },
    
  ]
