### ISSUE TITLE
Update Terms and Conditions

### ISSUE THREAD

**Issue by lasyaEd** [umcchavali/t-c#14]
Rearrange slack.txt and google maps.txt into tech company folder/put them into appropriate folders

Add more terms and conditions .txt files. Example: Healthcare tc (companies of your choice).

We need 6 more tc in electronics, 9 more in E-commerce, 9 more in cars.

**Comment by Hiranyabandi** [comment]
[updates queries and responses.json](https://github.com/user-attachments/files/17853589/updates.queries.and.responses.json)
