### ISSUE TITLE
Document Systematic Testing

### ISSUE THREAD

**Issue by lasyaEd** [umcchavali/t-c#16]
1. Performance metrics
2. Reliability measures
3. Areas for improvement
4. Test suite setup - Updated the queriesandresponses.json file in the repo.

**Comment by lasyaEd** [comment]
Areas for improvement:

<img width="1108" alt="image" src="https://github.com/user-attachments/assets/0c5d29c5-538a-4cab-98cf-f8c2662aaa83">

**Comment by lasyaEd** [comment]
<img width="1114" alt="error" src="https://github.com/user-attachments/assets/88531506-146d-4745-8705-f15365c7d714">

**Comment by lasyaEd** [comment]
Example of performance metrics:
For test case:

  - input: Can I redeem my Chick-fil-A One points at all locations?
  - actual output: The context does not explicitly state whether Chick-fil-A One points can be redeemed at all locations. It focuses on the conditions under which points are deducted or restored and mentions the company's right to limit reward redemptions and the consequences of fraudulent activities. For specific location redemption policies, it would be best to consult Chick-fil-A directly or refer to their official terms and conditions.
  - expected output: No, Chick-fil-A One points can only be redeemed at participating Chick-fil-A restaurants. Not all locations may participate in the rewards program, so it's best to check with your local Chick-fil-A to confirm if they accept Chick-fil-A One points.
  - context: None
  - retrieval context: ["Points will be subtracted from the Member's Chick-fil-A One account immediately when a Reward is requested based on the total Points for the requested Reward. Points will be restored to a Member's Chick-fil-A One account only in the event Chick fil A determines, in its sole and absolute discretion, that the Reward requested by that Member is unavailable or cannot be delivered. Chick-fil-A reserves the right to limit the redemption of specific Rewards and limit the number of Rewards available at any particular Membership Tier.\n\nAttempts to redeem single use offers and verification codes for Rewards multiple times or through multiple users constitutes fraud and may result in the termination or suspension of your Chick-fil-A One account."]

======================================================================

Metrics Summary

  - ✅ Correctness (GEval) (score: 0.5376252185513012, threshold: 0.5, strict: False, evaluation model: gpt-4o, reason: The actual output provides specific instructions for a contest entry which aligns with the expected output's guideline to follow specific instructions, but it lacks the broader advice about visiting official pages or reading rules and guidelines., error: None)
  - ✅ Faithfulness (score: 1.0, threshold: 0.7, strict: False, evaluation model: gpt-4, reason: None, error: None)
  - ✅ Contextual Relevancy (score: 1.0, threshold: 1.0, strict: False, evaluation model: gpt-4, reason: The score is 1.00 because the retrieval context perfectly aligns with the input question regarding submitting a contest entry for BurgerKing, with no noted irrelevancies., error: None)

**Comment by lasyaEd** [comment]
![image](https://github.com/user-attachments/assets/e49257aa-849a-4076-bcb1-32918f8cb6cf)

**Comment by lasyaEd** [comment]
correctness measure: https://docs.confident-ai.com/docs/metrics-llm-evals
faithfullness: https://docs.confident-ai.com/docs/metrics-faithfulness
answer relevancy: https://docs.confident-ai.com/docs/metrics-answer-relevancy

**Comment by lasyaEd** [comment]
Adding test_results to repo, added a new metric:

**Comment by samanthajmichael** [comment]
Edited Lasya's comment to include write up paragraphs for each metric.

**Comment by samanthajmichael** [comment]
3. Areas of Improvement: 
Add evaluation of our LLM with another LLM as judge. 
https://hamel.dev/blog/posts/llm-judge/
