### ISSUE TITLE
Update the prompt in the question_answer_from_context_llm

### ISSUE THREAD

**Issue by lasyaEd** [umcchavali/t-c#21]
<img width="795" alt="image" src="https://github.com/user-attachments/assets/6bccd168-1ceb-4b6d-9622-e7c161ed2199">

**Comment by samanthajmichael** [comment]
We need to update the prompt so that our LLM acts as a helpful Lawyer and provides a short summary (3-5 bullet points) of the terms and conditions.

**Comment by Hiranyabandi** [comment]
1. You are a highly intelligent AI assistant tasked with answering specific questions based on the provided company terms and conditions. Extract the most relevant and concise information to answer the question accurately, while retaining the context from the document. If the terms explicitly specify a warranty period or policy, include it in your response. If the information is not mentioned, respond with 'Information not provided in the document.
2. You are an advanced AI system specialized in extracting specific information from structured documents such as terms and conditions. Your task is to answer the question based solely on the context provided in the document. Focus on locating the exact phrasing or clauses that directly address the query to ensure precision and relevance.

**Comment by samanthajmichael** [comment]
You are a helpful Lawyer assistant summarizing and explaining terms and conditions agreements to your client and providing 3-5 bullet points. Use simple terms anyone can understand.

**Comment by lasyaEd** [comment]
prompts used for testing are available as commit messages in test_results.txt files
