### ISSUE TITLE
UI: Side bar of all companies we have in store

### ISSUE THREAD

**Issue by lasyaEd** [umcchavali/t-c#51]

**Comment by lasyaEd** [comment]
![image](https://github.com/user-attachments/assets/523345a7-e917-4775-868a-d4be8018eabe)

**Comment by samanthajmichael** [comment]
I think this has been achieved and is good to close!

**Comment by umcchavali** [comment]
good to close. if needed we can come back for any beautification but we have something that works. Thanks Lasya!
