### ISSUE TITLE
create QR code for the app so people can test during presentation

### ISSUE THREAD

**Issue by umcchavali** [umcchavali/t-c#52]

**Comment by lasyaEd** [comment]
https://www.qrcodechimp.com/

**Comment by wesslen** [comment]
Love the idea - I typically use bit.ly links (as they’re easier to communicate) - for example saying bit.ly/baymax is even easier (no need for phone and can type directly into laptop).

However:
1) are you using OpenAI or another paid API? By providing it it may cost more. Maybe not a ton like a few dollars. This is a minor thing so fine if yall are.
2) bigger question - can your app handle having 10-15 people on it at the same time? I don’t know. This was one reason I liked modal (I know it was a pain for other reasons) but the endpoints create new containers when more people hit it. While it would add more costs, it could scale. Are you sure your app can do the same?

please don’t feel obligated to do this - I love the progress talk have made today and like finishing up loose ends. But this is what a tool like locust can do for “load testing”: https://calmcode.io/course/locust/introduction

**Comment by lasyaEd** [comment]
<img width="466" alt="image" src="https://github.com/user-attachments/assets/38c391ab-6ad5-43cc-9e63-124a0ff2dcf3">

**Comment by lasyaEd** [comment]
![image](https://github.com/user-attachments/assets/f2750993-34bc-4ec2-861a-b520c85dd6da)

**Comment by lasyaEd** [comment]
https://bit.ly/baymaxtc
